# Generated by Django 5.0.2 on 2024-12-26 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystemapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='path',
            field=models.CharField(max_length=1024, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploaded_files/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='filesystemapp.folder'),
        ),
    ]
