# Generated by Django 5.0.2 on 2024-12-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystemapp', '0002_folder_path_alter_file_file_alter_file_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='path',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
