# Generated by Django 5.0.2 on 2024-12-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystemapp', '0003_alter_folder_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
